### ISSUE TITLE
Chrome + Edge Install Fails

### ISSUE THREAD

**Issue by jdarnton-akamai** [WPO-Foundation/wptagent-install#22]
Line 323
`wget -q -O - https://www.webpagetest.org/keys/google/linux_signing_key.pub | sudo apt-key add -`

results in 
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
```
and the script fails. However if you run
`wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -`

the results are
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

and the script can continue.

**Comment by jdarnton-akamai** [comment]
Appears Edge install fails in the same way for the same reason.

**Comment by pmeenan** [comment]
Trying to track down what happened to the proxy code in the main WebPageTest www code.  It used to rewrite those /keys/* requests and proxy them to the relevant origin (serving from cache for a while) to allow for installing in networks that blocked dl.google.com (China for example).

@tkadlec in case it rings a bell.

**Comment by pmeenan** [comment]
Either way, looks like those should all be changed to point to the direct keys for now and if it becomes a problem, figure it out then.

**Comment by jdarnton-akamai** [comment]
Thanks for the response. Yes, using the below in both the initial install and agent.sh creation worked fine:

```
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
```

**Comment by jdarnton-akamai** [comment]
Created pull request for this: https://github.com/WPO-Foundation/wptagent-install/pull/23
